# Generated by Django 4.2.4 on 2023-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicianInfo",
            fields=[
                (
                    "cli_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("cli_name", models.CharField(max_length=32)),
                ("cli_psw", models.CharField(max_length=32)),
            ],
        ),
    ]
