# Generated by Django 4.2.5 on 2023-10-09 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicianInfo",
            fields=[
                (
                    "cli_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("cli_name", models.CharField(max_length=32)),
                ("cli_psw", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                ("pa_id", models.AutoField(primary_key=True, serialize=False)),
                ("cli_id", models.CharField(default=0, max_length=6)),
                ("pa_name", models.CharField(max_length=32)),
                ("pa_psw", models.CharField(max_length=32)),
                ("age", models.SmallIntegerField(default=0)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=6,
                    ),
                ),
                ("info", models.TextField()),
                ("create_time", models.DateTimeField(default=datetime.datetime.now)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
