# Generated by Django 3.2.20 on 2023-09-05 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=32)),
                ('ad_psw', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('pa_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pa_name', models.CharField(max_length=32)),
                ('pa_psw', models.CharField(max_length=32)),
                ('age', models.SmallIntegerField(default=0)),
                ('info', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
