# Generated by Django 3.2.20 on 2023-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_admininfo_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
