# Generated by Django 3.2.20 on 2023-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_delete_admininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='cli_id',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
