# Generated by Django 4.2.4 on 2023-09-09 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianInfo',
            fields=[
                ('cli_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cli_name', models.CharField(max_length=32)),
                ('cli_psw', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('pa_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cli_id', models.CharField(default=0, max_length=6)),
                ('pa_name', models.CharField(max_length=32)),
                ('pa_psw', models.CharField(max_length=32)),
                ('age', models.SmallIntegerField(default=0)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('info', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
