# Generated by Django 4.2.4 on 2023-10-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUnlock',
            fields=[
                ('id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_unlocks', models.IntegerField(default=0)),
                ('unlocks_0_2', models.IntegerField(db_column='0_2_unlocks', default=0)),
                ('unlocks_3_5', models.IntegerField(db_column='3_5_unlocks', default=0)),
                ('unlocks_6_8', models.IntegerField(db_column='6_8_unlocks', default=0)),
                ('unlocks_9_11', models.IntegerField(db_column='9_11_unlocks', default=0)),
                ('unlocks_12_14', models.IntegerField(db_column='12_14_unlocks', default=0)),
                ('unlocks_15_17', models.IntegerField(db_column='15_17_unlocks', default=0)),
                ('unlocks_18_20', models.IntegerField(db_column='18_20_unlocks', default=0)),
                ('unlocks_21_23', models.IntegerField(db_column='21_23_unlocks', default=0)),
            ],
            options={
                'db_table': 'daily_unlock',
            },
        ),
        migrations.DeleteModel(
            name='ClinicianInfo',
        ),
        migrations.DeleteModel(
            name='PatientInfo',
        ),
    ]
