# Generated by Django 4.2.4 on 2023-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_clinicianinfo_delete_patientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_unlocks', models.IntegerField(default=0)),
                ('unlocks_0_2', models.IntegerField(db_column='0_2_unlocks', default=0)),
                ('unlocks_3_5', models.IntegerField(db_column='3_5_unlocks', default=0)),
                ('unlocks_6_8', models.IntegerField(db_column='6_8_unlocks', default=0)),
                ('unlocks_9_11', models.IntegerField(db_column='9_11_unlocks', default=0)),
                ('unlocks_12_14', models.IntegerField(db_column='12_14_unlocks', default=0)),
                ('unlocks_15_17', models.IntegerField(db_column='15_17_unlocks', default=0)),
                ('unlocks_18_20', models.IntegerField(db_column='18_20_unlocks', default=0)),
                ('unlocks_21_23', models.IntegerField(db_column='21_23_unlocks', default=0)),
            ],
            options={
                'db_table': 'daily_unlock',
                'unique_together': {('date',)},
            },
        ),
    ]
