# Generated by Django 4.2.4 on 2023-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dailyunlock_delete_clinicianinfo_delete_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyunlock',
            name='device_id',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dailyunlock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyunlock',
            unique_together={('date', 'device_id')},
        ),
        migrations.CreateModel(
            name='DailyDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('device_id', models.CharField(default=0, max_length=150)),
                ('total_duration', models.FloatField(default=0.0)),
                ('duration_0_2', models.FloatField(db_column='0_2_duration', default=0.0)),
                ('duration_3_5', models.FloatField(db_column='3_5_duration', default=0.0)),
                ('duration_6_8', models.FloatField(db_column='6_8_duration', default=0.0)),
                ('duration_9_11', models.FloatField(db_column='9_11_duration', default=0.0)),
                ('duration_12_14', models.FloatField(db_column='12_14_duration', default=0.0)),
                ('duration_15_17', models.FloatField(db_column='15_17_duration', default=0.0)),
                ('duration_18_20', models.FloatField(db_column='18_20_duration', default=0.0)),
                ('duration_21_23', models.FloatField(db_column='21_23_duration', default=0.0)),
            ],
            options={
                'db_table': 'daily_durations',
                'unique_together': {('date', 'device_id')},
            },
        ),
    ]
