# Generated by Django 4.2.4 on 2023-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailyunlock_device_id_alter_dailyunlock_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('device_id', models.CharField(max_length=150)),
                ('Monday', models.IntegerField(null=True)),
                ('Tuesday', models.IntegerField(null=True)),
                ('Wednesday', models.IntegerField(null=True)),
                ('Thursday', models.IntegerField(null=True)),
                ('Friday', models.IntegerField(null=True)),
                ('Saturday', models.IntegerField(null=True)),
                ('Sunday', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'weekly_unlocks',
                'unique_together': {('week_start_date', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('device_id', models.CharField(max_length=150)),
                ('Monday', models.FloatField(null=True)),
                ('Tuesday', models.FloatField(null=True)),
                ('Wednesday', models.FloatField(null=True)),
                ('Thursday', models.FloatField(null=True)),
                ('Friday', models.FloatField(null=True)),
                ('Saturday', models.FloatField(null=True)),
                ('Sunday', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'weekly_durations',
                'unique_together': {('week_start_date', 'device_id')},
            },
        ),
    ]
