# Generated by Django 4.2.4 on 2023-10-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyUnlock',
        ),
    ]
