# Generated by Django 4.2.4 on 2023-10-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_dailyunlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_unlocks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_unlock',
            },
        ),
    ]
