# Generated by Django 4.2.4 on 2023-10-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_weeklyunlock_weeklyduration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyduration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyunlock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyduration',
            name='week_start',
            field=models.DateField(default=0.0),
        ),
        migrations.AddField(
            model_name='weeklyunlock',
            name='week_start',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Friday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Monday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Saturday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Sunday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Thursday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Tuesday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='Wednesday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyduration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Friday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Monday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Saturday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Sunday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Thursday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Tuesday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='Wednesday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyunlock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyduration',
            unique_together={('week_start', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyunlock',
            unique_together={('week_start', 'device_id')},
        ),
        migrations.RemoveField(
            model_name='weeklyduration',
            name='week_start_date',
        ),
        migrations.RemoveField(
            model_name='weeklyunlock',
            name='week_start_date',
        ),
    ]
