# Generated by Django 4.2.4 on 2023-10-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyunlock',
            table='daily_unlock_stats',
        ),
    ]
