# Generated by Django 4.2.4 on 2023-10-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_dailyunlock_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_0_2',
            field=models.IntegerField(db_column='0_2_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_12_14',
            field=models.IntegerField(db_column='12_14_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_15_17',
            field=models.IntegerField(db_column='15_17_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_18_20',
            field=models.IntegerField(db_column='18_20_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_21_23',
            field=models.IntegerField(db_column='21_23_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_3_5',
            field=models.IntegerField(db_column='3_5_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_6_8',
            field=models.IntegerField(db_column='6_8_unlocks', default=0),
        ),
        migrations.AddField(
            model_name='dailyunlock',
            name='unlocks_9_11',
            field=models.IntegerField(db_column='9_11_unlocks', default=0),
        ),
        migrations.AlterField(
            model_name='dailyunlock',
            name='id',
            field=models.AutoField(db_column='_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dailyunlock',
            table='daily_unlock',
        ),
    ]
